version: '3.8'

# Akses container bisa 
# - menggunakan port forwarding
# - menggunakan ip yang diassign dinamis

# services:
#   app:
#     image: node:21-alpine
#     command: sh -c "npm install && npm run dev"
#     ports:
#       - 8888:8888
#     working_dir: /app
#     volumes:
#       - ./:/app
#     environment:
#       - DB_HOST=localhost
#       - DB_USER=postgres
#       - DB_PASSWORD=1
#       - DB_NAME=node_monolith
#       - DB_PORT=5435
#   postgresdb:
#     image: postgres
#     ports:
#       - 5435:5432
#     volumes:
#       - db:/var/lib/postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=1
#       - POSTGRES_DB=node_monolith

# volumes:
#   db:

services:
  webapp:
    build: .
    ports:
      - 8081:8888
    environment:
      - DATABASE_URL=postgresql://postgres:1@db:5432/postgres?sslmode=disable
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      # Init DB dijelaskan di hub.docker.com/_/postgres => setion Initialization Scripts
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql
    environment:
      - POSTGRES_PASSWORD=1